#! /bin/bash

pushd "$(dirname $0)"
cd src

executable="megatokyo-dl"
zipfile="${executable}.zip"
temp="temp"

# Create new pyc files
rm -rf __pycache__
python3 -m compileall .
zip -r "$zipfile" __main__.py __pycache__ *py
cd ..

rm -f "$executable"
mv "src/$zipfile" "$temp"

echo "#! /usr/bin/env python3" > "$executable"
cat "$temp" >> "$executable"
rm "$temp"

chmod +x "$executable"

popd

